// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopOne.Web.Data;

namespace WorkshopOne.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200901193413_AddChurchAndDistrict")]
    partial class AddChurchAndDistrict
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkshopOne.Common.Entities.church", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DistrictId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("churches");
                });

            modelBuilder.Entity("WorkshopOne.Common.Entities.Countryside", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("countrysides");
                });

            modelBuilder.Entity("WorkshopOne.Common.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountrysideId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountrysideId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("WorkshopOne.Common.Entities.church", b =>
                {
                    b.HasOne("WorkshopOne.Common.Entities.District")
                        .WithMany("Churches")
                        .HasForeignKey("DistrictId");
                });

            modelBuilder.Entity("WorkshopOne.Common.Entities.District", b =>
                {
                    b.HasOne("WorkshopOne.Common.Entities.Countryside")
                        .WithMany("Districts")
                        .HasForeignKey("CountrysideId");
                });
#pragma warning restore 612, 618
        }
    }
}
